language: ruby

os:
  - linux
  - osx

sudo: required

rvm:
  - 2.4.1
  - 2.3.3
  - 2.2.6
  - jruby-9.1.8.0

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: jruby-9.1.8.0

notifications:
  email: false

env:
  - DEBUG=1 IPV4=1

script:
  - bundle exec rake build
  - bundle exec rspec -t ~multicast:ipv6 -t ~performance
