language: ruby

os:
  - linux
  - osx

rvm:
  - 2.1
  - jruby
  - rbx-head

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: jruby
    - rvm: rbx-head

notifications:
  email: false

script:
  - bundle exec rake build
  - DEBUG=1 bundle exec rspec -t ~multicast:ipv6 -t ~performance
