language: ruby

os:
  - linux
  - osx

sudo: required

rvm:
  - 2.5
  - 2.4
  - 2.3
  - jruby-9.1

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - rvm: 2.5
    - rvm: jruby-9.1

notifications:
  email: false

env:
  - DEBUG=1 IPV4=1

before_install:
  # work around https://github.com/travis-ci/travis-ci/issues/8969
  - travis_retry gem update --system

script:
  - bundle exec rake build
  - bundle exec rspec -t ~multicast:ipv6 -t ~performance
